#' @name plotspict.growth
#' @title Plot estimated time-varying growth
#' @details Plots estimated time-varying growth
#' @param rep A result report as generated by running fit.spict.
#' @param logax Take log of y-axis? default: FALSE
#' @param main Title of plot.
#' @param ylim Limits for y-axis.
#' @param xlim Limits for x-axis.
#' @param xlab Label of x-axis.
#' @param plot.ci If TRUE 95\% CIs are included.
#' @param stamp Stamp plot with this character string.
#' @param CI Confidence intervals to be calculated, e.g. 0.9 for the 90\%
#'     confidence intervals. By default (CI = 0.95), the 95\% confidence
#'     intervals are estimated.
#'
#' @return Nothing.
#'
#' @export
plotspict.growth <- function(rep, logax=FALSE, main='Time-varying growth', ylim=NULL,
                             xlim=NULL, xlab='Time', plot.ci=TRUE, stamp=get.version(), CI = 0.95){
  if (!'sderr' %in% names(rep) & rep$inp$timevaryinggrowth){
    log <- ifelse(logax, 'y', '')
    inp <- rep$inp
    rre <- get.par('logrre', rep, exp=TRUE, CI = CI)
    r <- get.par('logr', rep, exp=TRUE, CI = CI)[, 2]
    time <- inp$time
    if (is.null(ylim)){
      if (length(ylim) != 2){
        if (plot.ci){
          ylim <- range(rre[, 1:3], na.rm=TRUE)
        } else {
          ylim <- range(rre[, 2], na.rm=TRUE)
        }
      }
    }
    if (is.null(xlim)){
      if (length(xlim) != 2){
        xlim <- range(c(time, tail(time, 1) + 0.5))
      }
    }
    plot(time, rre[, 2], typ='n', xlab=xlab, ylab=expression(r[t]), ylim=ylim,
         xlim=xlim, log=log, main=main)
    gr <- 0.7
    cicol2 <- rgb(0, gr, 0, 0.1)
    abline(h=r, col=1)
    if (plot.ci){
      polygon(c(time, rev(time)), c(rre[, 1], rev(rre[, 3])), col=cicol2, border=cicol2)
      cicol3 <- rgb(0, gr, 0, 0.2)
      lines(time, rre[, 1], col=cicol3, lty=1, lwd=1)
      lines(time, rre[, 3], col=cicol3, lty=1, lwd=1)
    }
    abline(v=inp$time[inp$indlastobs], col='gray')
    lines(time, rre[, 2], col=rgb(0, gr, 0), lwd=1.5)
    box(lwd=1.5)
    txt.stamp(stamp)
  }
}


